### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?

### ISSUE THREAD

**Issue by PayneJay** [lyric315/UIPerforance#2]
有人遇到以下问题吗？
```java
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.lyri.uiperformance.core.view.MonitorView.attachMonitorViewToWindown(MonitorView.java:175)
        at com.lyri.uiperformance.core.view.MonitorView.run(MonitorView.java:135)
```

**Comment by SpakeBrony** [comment]
我也是这个错误
